/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbms;

//import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;

/**
 *
 * @author kumai
 */
public class AddNewDonor extends javax.swing.JFrame {

    /**
     * Creates new form AddNewDonor
     */
    public AddNewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtxName = new javax.swing.JTextField();
        txtBlood = new javax.swing.JComboBox<>();
        txtDob = new javax.swing.JTextField();
        txtMob = new javax.swing.JTextField();
        txtGender = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtFather = new javax.swing.JTextField();
        txtMother = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtSave = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Add New Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 650, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("New Donor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 122, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 122, 147, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 174, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Blood Group");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 223, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 272, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mobile No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 328, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 381, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 67, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Father Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mother Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 97, -1));

        txtxName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 171, 168, -1));

        txtBlood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        getContentPane().add(txtBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 220, 168, -1));

        txtDob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        getContentPane().add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 269, 166, -1));

        txtMob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 325, 166, -1));

        txtGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 378, 166, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 168, -1));

        txtFather.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 168, -1));

        txtMother.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 168, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 650, 10));

        txtSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\save.png")); // NOI18N
        txtSave.setText("Save");
        txtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 438, -1, -1));

        Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\Update details.png")); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\Exit application.png")); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\all page background image.png")); // NOI18N
        jLabel12.setText("e");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaveActionPerformed
        if (txtxName.getText().length() == 0 || !txtxName.getText().matches("[a-zA-Z]+(\\s[a-zA-Z]+)*")) {
            JOptionPane.showMessageDialog(this, "Invalid Name!");
        } else if (txtFather.getText().length() == 0 || !txtFather.getText().matches("[a-zA-Z]+(\\s[a-zA-Z]+)*")) {
            JOptionPane.showMessageDialog(this, "Invalid Father Name!");
        } else if (txtMother.getText().length() == 0 || !txtMother.getText().matches("[a-zA-Z]+(\\s[a-zA-Z]+)*")) {
            JOptionPane.showMessageDialog(this, "Invalid Mother Name!");

        } else if (txtMob.getText().length() == 0 || !txtMob.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number!");
        } else if (!txtEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email!");
        } else {
            try {

                //Set Driver Of SQL
                Class.forName("com.mysql.jdbc.Driver");

                //Set Connection with localhost server
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bbms", "root", "");

                // INSERT Query of SQL using to get insert data
                String cardInsertStatement = "INSERT INTO AddDonor (FullName, MotherName, FatherName, BloodGroup, DateOfBirth, MobileNum, Gender, Email) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement cptst = conn.prepareStatement(cardInsertStatement, java.sql.Statement.RETURN_GENERATED_KEYS);

                cptst.setString(1, txtxName.getText());
                cptst.setString(2, txtMother.getText());
                cptst.setString(3, txtFather.getText());
                cptst.setString(4, txtBlood.getSelectedItem().toString());
                cptst.setString(5, txtDob.getText());
                cptst.setString(6, txtMob.getText());
                cptst.setString(7, txtGender.getSelectedItem().toString());
                cptst.setString(8, txtEmail.getText());
                cptst.executeUpdate();
//            ResultSet rss = cptst.getGeneratedKeys();
//            recordNumber = 0;
//            if (rss.next()) {
//                recordNumber = rss.getInt(1);
//            }
//            System.out.println(recordNumber);
                conn.close();
                JOptionPane.showMessageDialog(this, "Donor Has Been Added Successfully!");

                Home ts = new Home();
                ts.setVisible(true);
                this.setVisible(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e + "Something went wrong! Try again later");

            }
        }
    }//GEN-LAST:event_txtSaveActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        txtxName.setText("");
        txtFather.setText("");
        txtMother.setText("");
        txtDob.setText("");
        txtMob.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null , "Do you really want to Close? ", "Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> txtBlood;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFather;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JTextField txtMob;
    private javax.swing.JTextField txtMother;
    private javax.swing.JButton txtSave;
    private javax.swing.JTextField txtxName;
    // End of variables declaration//GEN-END:variables
}
