/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author kumai
 */
public class AddNewAcceptor extends javax.swing.JFrame {

    /**
     * Creates new form AddNewAcceptor
     */
    public AddNewAcceptor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textDob = new javax.swing.JTextField();
        textMob = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textFather = new javax.swing.JTextField();
        textMother = new javax.swing.JTextField();
        textBlood = new javax.swing.JComboBox<>();
        textGender = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        SaveBtn = new javax.swing.JButton();
        RestBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("ADD ACCEPTOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 6, 287, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 640, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Blood Group");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date Of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mobile No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Email Id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Father Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mother Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        textName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 156, -1));

        textDob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 156, -1));

        textMob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 156, -1));

        textEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 168, -1));

        textFather.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 168, -1));

        textMother.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(textMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 168, -1));

        textBlood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", " ", " " }));
        getContentPane().add(textBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 156, -1));

        textGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(textGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 156, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 610, 10));

        SaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\save.png")); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        RestBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RestBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\Update details.png")); // NOI18N
        RestBtn.setText("Reset");
        RestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        CloseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\Exit application.png")); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\all page background image.png")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
          int a =JOptionPane.showConfirmDialog(null , "Do you really want to Close? ", "Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void RestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestBtnActionPerformed
        // TODO add your handling code here:
         textName.setText("");
        textFather.setText("");
        textMother.setText("");
        textDob.setText("");
        textMob.setText("");
        textEmail.setText("");
    }//GEN-LAST:event_RestBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
               if (textName.getText().length() == 0 || !textName.getText().matches("[a-zA-Z]+(\\s[a-zA-Z]+)*")) {
            JOptionPane.showMessageDialog(this, "Invalid Name!");
        } else if (textFather.getText().length() == 0 || !textFather.getText().matches("[a-zA-Z]+(\\s[a-zA-Z]+)*")) {
            JOptionPane.showMessageDialog(this, "Invalid Father Name!");
        } else if (textMother.getText().length() == 0 || !textMother.getText().matches("[a-zA-Z]+(\\s[a-zA-Z]+)*")) {
            JOptionPane.showMessageDialog(this, "Invalid Mother Name!");

        } else if (textMob.getText().length() == 0 || !textMob.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number!");
        } else if (!textEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Email!");
        } else {
            try {

                //Set Driver Of SQL
                Class.forName("com.mysql.jdbc.Driver");

                //Set Connection with localhost server
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bbms", "root", "");

                // INSERT Query of SQL using to get insert data
                String cardInsertStatement = "INSERT INTO AddDonor (FullName, MotherName, FatherName, BloodGroup, DateOfBirth, MobileNum, Gender, Email) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement cptst = conn.prepareStatement(cardInsertStatement, java.sql.Statement.RETURN_GENERATED_KEYS);

                cptst.setString(1, textName.getText());
                cptst.setString(2, textMother.getText());
                cptst.setString(3, textFather.getText());
                cptst.setString(4, textBlood.getSelectedItem().toString());
                cptst.setString(5, textDob.getText());
                cptst.setString(6, textMob.getText());
                cptst.setString(7, textGender.getSelectedItem().toString());
                cptst.setString(8, textEmail.getText());
                cptst.executeUpdate();
//            ResultSet rss = cptst.getGeneratedKeys();
//            recordNumber = 0;
//            if (rss.next()) {
//                recordNumber = rss.getInt(1);
//            }
//            System.out.println(recordNumber);
                conn.close();
                JOptionPane.showMessageDialog(this, "Acceptor Has Been Added Successfully!");

                Home ts = new Home();
                ts.setVisible(true);
                this.setVisible(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e + "Something went wrong! Try again later");

            }
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewAcceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewAcceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewAcceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewAcceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewAcceptor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton RestBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> textBlood;
    private javax.swing.JTextField textDob;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFather;
    private javax.swing.JComboBox<String> textGender;
    private javax.swing.JTextField textMob;
    private javax.swing.JTextField textMother;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
