/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbms;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kumai
 */
public class Increase extends javax.swing.JFrame {

    /**
     * Creates new form Increase
     */
    public Increase() {
        initComponents();
        updateTable();
    }

    public void updateTable() {
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bbms", "root", "");

            // Assuming you have a table named 'donors' with columns 'blood_type'
            String query = "SELECT COUNT(*) FROM adddonor WHERE bloodgroup = ?";
            try (PreparedStatement statement = conn.prepareStatement(query)) {
                // Update the counts for A+, B+, C+
                statement.setString(1, "A+");
                ResultSet resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    txtap.setText("A+: " + String.valueOf(resultSet.getInt(1)));
                }

                statement.setString(1, "A-");
                resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    txtan.setText("A-: " + String.valueOf(resultSet.getInt(1)));
                }

                statement.setString(1, "B+");
                resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    txtbp.setText("B+: "+String.valueOf(resultSet.getInt(1)));
                }
                
                statement.setString(1, "B-");
                resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    txtbn.setText("B+: "+String.valueOf(resultSet.getInt(1)));
                }
                
                statement.setString(1, "AB+");
                resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    txtabp.setText("AB+: "+String.valueOf(resultSet.getInt(1)));
                }
                
                 statement.setString(1, "AB-");
                resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    txtabn.setText("AB-: "+String.valueOf(resultSet.getInt(1)));
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtap = new javax.swing.JLabel();
        txtan = new javax.swing.JLabel();
        txtbp = new javax.swing.JLabel();
        txtbn = new javax.swing.JLabel();
        txtabp = new javax.swing.JLabel();
        txtabn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Stock AvAiLAble ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\Exit application.png")); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 461, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 210, 40));

        txtap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtap.setText("A+: 12");
        getContentPane().add(txtap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 40));

        txtan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtan.setText("A+ :69");
        getContentPane().add(txtan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 40));

        txtbp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbp.setText("A+ :69");
        getContentPane().add(txtbp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 40));

        txtbn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbn.setText("A+ :69");
        getContentPane().add(txtbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 110, 40));

        txtabp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtabp.setText("A+ :69");
        getContentPane().add(txtabp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 110, 40));

        txtabn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtabn.setText("A+ :69");
        getContentPane().add(txtabn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\kumai\\Desktop\\Pictur\\all page background image.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int a =JOptionPane.showConfirmDialog(null , "Do you really want to Close? ", "Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Increase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Increase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Increase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Increase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Increase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtabn;
    private javax.swing.JLabel txtabp;
    private javax.swing.JLabel txtan;
    private javax.swing.JLabel txtap;
    private javax.swing.JLabel txtbn;
    private javax.swing.JLabel txtbp;
    // End of variables declaration//GEN-END:variables
}
